// 模型匣 —— 内置供应商名单解析单元测试（node:test，零依赖）

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { extractPiProviderIds, resolveBuiltinProviderIds } from "../lib/builtin.js";

// ── extractPiProviderIds：从 models.generated.js 文本提取 MODELS 键 ──
test("extractPiProviderIds 提取 MODELS 对象键", () => {
  const source = `// This file is auto-generated by scripts/generate-models.ts
import { DEEPSEEK_MODELS } from "./providers/deepseek.models.js";
import { OPENAI_CODEX_MODELS } from "./providers/openai-codex.models.js";
export const MODELS = {
    "deepseek": DEEPSEEK_MODELS,
    "openai-codex": OPENAI_CODEX_MODELS,
    "opencode-go": SOME_MORE_MODELS,
};`;
  const ids = extractPiProviderIds(source);
  // 提取按文件出现顺序（MODELS 键序）
  assert.deepEqual([...ids], ["deepseek", "openai-codex", "opencode-go"]);
});

test("extractPiProviderIds 忽略 import 与空对象", () => {
  const ids = extractPiProviderIds("import { x } from './x.js';\nexport const MODELS = {};");
  assert.equal(ids.size, 0);
});

// ── resolveBuiltinProviderIds：扫 artifacts/server 版本目录取最新 ──
function makeArtifacts(root, versionDir, providerIds) {
  const file = path.join(
    root,
    "artifacts", "server", versionDir,
    "node_modules", "@earendil-works", "pi-ai", "dist",
    "models.generated.js",
  );
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const lines = providerIds.map((id) => `    "${id}": M,`).join("\n");
  fs.writeFileSync(file, `export const MODELS = {\n${lines}\n};\n`, "utf-8");
}

test("resolveBuiltinProviderIds 从最新版本目录取名单（旧目录缺文件也跳过）", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "moxingxia-builtin-"));
  try {
    // 旧版本没有 pi-ai models.generated.js（例如结构变化）
    const staleDir = path.join(root, "artifacts", "server", "0.686.15-win32-x64");
    fs.mkdirSync(staleDir, { recursive: true });
    // 新版本有
    makeArtifacts(root, "0.712.5-win32-x64", ["deepseek", "minimax", "openai-codex"]);

    const ids = resolveBuiltinProviderIds(root);
    assert.ok(ids instanceof Set);
    assert.equal(ids.has("deepseek"), true);
    assert.equal(ids.has("openai-codex"), true);
    assert.equal(ids.has("gemini"), false);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test("resolveBuiltinProviderIds 版本号大的目录优先", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "moxingxia-builtin-"));
  try {
    makeArtifacts(root, "0.712.5-win32-x64", ["deepseek", "gemini"]);
    makeArtifacts(root, "0.712.15-win32-x64", ["deepseek", "kimi"]);
    const ids = resolveBuiltinProviderIds(root);
    assert.equal(ids.has("kimi"), true);
    assert.equal(ids.has("gemini"), false);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test("resolveBuiltinProviderIds 无 artifacts 目录时返回 null（降级）", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "moxingxia-builtin-"));
  try {
    assert.equal(resolveBuiltinProviderIds(root), null);
    assert.equal(resolveBuiltinProviderIds(path.join(root, "不存在")), null);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test("resolveBuiltinProviderIds 名单为空文件时视为不可用，继续/返回 null", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "moxingxia-builtin-"));
  try {
    const file = path.join(
      root, "artifacts", "server", "0.712.5-win32-x64",
      "node_modules", "@earendil-works", "pi-ai", "dist", "models.generated.js",
    );
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, "export const MODELS = {};\n", "utf-8");
    assert.equal(resolveBuiltinProviderIds(root), null);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});